image: docker:stable

services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

deploying:
  before_script:
    - docker login --password $CI_REGISTRY_PASSWORD --username $CI_REGISTRY_USER $CI_REGISTRY
  script:
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master
